[package]
name = "tavern_service"
version = "0.1.0"
authors = ["Michael Shaw <michaeljshaw@gmail.com>"]

[dependencies]
time = "*"
rand = "*"
tavern_core = { path = "../core" }
aphid = { path = "../aphid" }