[package]
name = "tavern_core"
version = "0.1.0"
authors = ["Michael Shaw <michaeljshaw@gmail.com>"]

[dependencies]
rand = "0.3"
time = "0.1"
pad = "0.1"
quickersort = "2.2"
colored = "1.4"

serde = "1.0"
serde_derive = "1.0"

aphid = { git = "https://github.com/michaelshaw/aphid" }
